var ListingConstants = {
  FETCHLISTINGS: "FETCHLISTINGS",
  FETCHLISTING: "FETCHLISTING",
  FILTEREDLISTINGS: "FILTEREDLISTINGS",
  CREATELISTING: "CREATELISTING"
};

module.exports = ListingConstants;
